I'm sorry, but an uncaught exception occurred.

While running game code:
  File "game/script.rpy", line 50, in script
    show screen drag_sample3
  File "renpy/common/000statements.rpy", line 588, in execute_show_screen
    renpy.show_screen(name, *args, **kwargs)
Exception: Screen drag_sample3 is not known.


-- Full Traceback ------------------------------------------------------------

Full traceback:
  File "game/script.rpy", line 50, in script
    show screen drag_sample3
  File "C:\Users\yello\Desktop\renpy-8.0.3-sdk\renpy\ast.py", line 2232, in execute
    self.call("execute")
  File "C:\Users\yello\Desktop\renpy-8.0.3-sdk\renpy\ast.py", line 2220, in call
    return renpy.statements.call(method, parsed, *args, **kwargs)
  File "C:\Users\yello\Desktop\renpy-8.0.3-sdk\renpy\statements.py", line 281, in call
    return method(parsed, *args, **kwargs)
  File "renpy/common/000statements.rpy", line 588, in execute_show_screen
    renpy.show_screen(name, *args, **kwargs)
  File "C:\Users\yello\Desktop\renpy-8.0.3-sdk\renpy\display\screen.py", line 1185, in show_screen
    raise Exception("Screen %s is not known.\n" % (name[0],))
Exception: Screen drag_sample3 is not known.


Windows-10-10.0.22621 AMD64
Ren'Py 8.0.3.22090809
Nausea 1.0
Sat Jan 21 01:34:44 2023
